baseURL = "https://trytonvanmeer.dev/"
title = "Tryton"
languageCode = "en-us"
pygmentsUseClasses = true

[menu]
[[menu.nav]]
name = "About"
url = "/about/"
weight = 1

[[menu.nav]]
name = "Blog"
url = "/blog/"
weight = 2
